arch:
 - arm64
 - amd64
os:
 - linux
 - osx
osx_image: xcode12.2
dist: focal
language: c
addons:
  apt:
    packages:
     - libtalloc-dev
     - check
     - liblua5.3-dev
  homebrew:
    packages:
     - lua@5.4
     - talloc
     - check
script:
  - ./configure
  - make
  - make test

