arch:
 - arm64
 - amd64
os:
 - linux
 - osx
osx_image: xcode12.2
dist: focal
language: c
addons:
  apt:
    packages:
     - lua5.4
     - liblua5.4-dev
     - libtalloc-dev
     - check
  homebrew:
    packages:
     - lua@5.4
     - libtalloc-dev
     - check
script:
  - make
  - (cd tests  ; ./runtests.sh)

