-- Color module for Galvinise
--
-- rgba/rgb/hsv() creates a color
-- 	The format is the same for all
-- 	rgba(r,g,b,a)
-- 		If A is ommitted it is assumed to be 255
--		If any value is between 0 and 1, it is assumed to be in 
--			that range.
--		If only one value is given it is used for all r,g,b, with 
--			a set to 255
--		If two values, you get the first as r,g,b and the last as a.
--	
--	rgba(0.5, 0.5, 0.5):	50% grey
--	rgb(128,128,128,255): 	Same; 50% grey
--
--
